config/routes.rb
Rails.application.routes.draw do
  resource :leagues, only: [:index]

  root 'leagues#index'

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resource :dashboard, only: [:show, :update]
    resources :leagues, only: [:show, :update] do
      resources :competitors, only: [:create, :destroy, :update]
      resources :matches, only: [:new, :create]
    end
    resources :competitors, only: [:show] do
      resources :matches, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  belongs_to :league
  has_and_belongs_to_many :matches

  validates_presence_of :name, :league_id

  def wins
    self.matches.won_by(self)
  end

  def losses
    self.matches.lost_by(self)
  end

  def results
    self.matches.reduce({}) do |results_hash, match|
      value = match.winner == self ? 'w' : 'l'
      round_symbol = :"r#{match.round_number}"
      results_hash[round_symbol] = value
      results_hash
    end
  end

end

app/models/league.rb
class League < ApplicationRecord
  has_many :matches
  has_many :competitors

  validates :name, :number_of_rounds, presence: true

  # this would ideally be a scope, but our schema architecture feels a little whack
  def current_leader
    self.competitors.max_by do |competitor|
      competitor.wins.count
    end
  end

  def array_of_rounds_possible
    Array (1..self.number_of_rounds)
  end

end

app/models/login_form.rb
class LoginForm
  include ActiveModel::Model

  attr_accessor(
    :username,
    :password
  )

  attr_reader :user

  validates :username, presence: true
  validates :password, presence: true

  def authenticated?
    @user = nil
    if valid?
      user = User.find_by_username(@username)
      if user && user.authenticate(@password)
        @user = user
      else
        @errors.add(:login, :message => "Username and/or password entered incorrectly")
      end
    end
    !!@user
  end

end

app/models/match.rb
class Match < ApplicationRecord

  attr_accessor :competitor_one_id, :competitor_two_id

  belongs_to :league
  has_and_belongs_to_many :competitors

  belongs_to :winner, class_name: :Competitor, required: false
  belongs_to :loser, class_name: :Competitor, required: false

  scope :from_round, ->(round_number) { where(round_number: round_number) }

  validates_presence_of :league_id

  scope :won_by, -> ( winner ){ where(winner: winner) }

  scope :lost_by, -> ( loser ){ where(loser: loser) }

  validate :validate_competitors

  def validate_competitors
    errors.add(:competitors, ': pick two to create a match') if competitors.size != 2
  end

  before_validation :load_competitors

  def load_competitors
    input = [self.competitor_one_id.to_i, self.competitor_two_id.to_i].uniq
    current = self.competitors.map {|c| c.id}

    add = input.reject do |i|
      i == 0 || current.include?(i)
    end

    remove = current.reject do |i|
      input.include?(i)
    end

    remove.each do |competitor_id|
      self.competitors -= [Competitor.find(competitor_id)]
    end

    add.each do |competitor_id|
      self.competitors <<  Competitor.find(competitor_id)
    end

    true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true

  has_secure_password
end

app/controllers/admin/competitors_controller.rb
class Admin::CompetitorsController < AdminController

  def create
    @league = League.find(params[:league_id])
    @league.competitors.create(competitor_form_params)
    redirect_to admin_league_path(@league)
  end

  def update
    @league = League.find(params[:league_id])
    competitor = Competitor.find(params[:id])
    competitor.update(competitor_form_params)
    redirect_to admin_league_path(@league)
  end

  def destroy
    @league = League.find(params[:league_id])
    competitor = Competitor.find(params[:id])
    competitor.destroy
    redirect_to admin_league_path(@league)
  end

  private

  def competitor_form_params
    params.require(:competitor).permit(:name)
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController

  def show
    @league1 = League.all.first
    @league2 = League.all.last
  end

  def update
    League.all.update(number_of_rounds: round_params)
    @league1 = League.all.first
    @league2 = League.all.last
    redirect_to admin_dashboard_path
  end

  private

  def round_params
    params[admin_dashboard_path][:rounds]
  end
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < AdminController

  def show
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])
    @league.update(name: league_name_params)
    redirect_to admin_league_path(@league)
  end

  private

  def league_name_params
    params[admin_league_path(@league)]["name"]
  end

end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < AdminController
  include ApplicationHelper

  def new
    @current_league = current_league
    @match = @current_league.matches.new
    options_for_form_new_match

  end

  def create
    @current_league = current_league
    @match = @current_league.matches.new(match_params)
    options_for_form_new_match

    if @match.save
      redirect_to '/admin/dashboard'
    else
      render :new
    end
  end

  def update
    match = Match.find(params[:id])
    match.winner = match.competitors.find(params[:competitor_id])
    index = match.competitors.find_index(match.winner)
    index == 0 ? match.loser = match.competitors[1] : match.loser = match.competitors[0]
    match.update_attribute(:winner_id, match.winner.id)
    match.update_attribute(:loser_id, match.loser.id)
    redirect_to admin_dashboard_path
  end

  private
  def match_params
    params.require(:match).permit(:round_number, :competitor_one_id, :competitor_two_id)
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
    @login_form = LoginForm.new
  end

  def create
    @login_form = LoginForm.new(login_form_params)

    if @login_form.authenticated?
      session[:user_id] = @login_form.user.id
      redirect_to '/admin/dashboard'
    else
      render 'admin/sessions/new'
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def login_form_params
    params.require(:login_form).permit(:username, :password)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    if session[:user_id] == nil
      session[:flash] = "You must log in to access that area"
      redirect_to new_admin_session_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  include LeagueViewHelper

  def index
    @league1 = League.all.first
    @league2 = League.all.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def current_league
  @current_league = League.find(params['league_id'])
end

def options_for_form_new_match
    @round_options = @current_league.array_of_rounds_possible

    @competitor_options = @current_league.competitors.collect do |p|
     [ p.name, p.id ]
    end
end


end

app/helpers/league_view_helper.rb
module LeagueViewHelper

  # def display_latest_current_round(league1, league2)
  #   p league1.current_round
  #   p league2.current_round
  #   if league1.current_round == league2.current_round
  #     league1.current_round
  #   elsif league1.current_round > league2.current_round
  #     league1.current_round
  #   else
  #     league2.current_round
  #   end
  # end

end

app/views/admin/_homepage_logout_nav_bar.html.erb
<div id='nav-bar-admin'>
  <div id="homepage">
    <%= button_to "Homepage", root_path, method: :get, :class => 'submit-buttons' %>
  </div>
    <div id="dashboard">
    <%= button_to "Go to Dashboard", '/admin/dashboard', method: :get, :class => 'submit-buttons' %>
  </div>
  <div id="logout">
    <%= button_to "Logout", '/admin/session', method: :delete, :class => 'submit-buttons' %>
  </div>
</div>

app/views/admin/dashboards/show.html.erb
<%= render 'admin/homepage_logout_nav_bar' %>

<h1>Greetings, Commissioner</h1>
<hr>
<div id="update-rounds">
  <h2>Rounds this season:</h2>
  <p id="rounds"><%= @league1.number_of_rounds %> rounds</p>
  <%= form_for admin_dashboard_path, method: :put do |form| %>
    <%= form.label :rounds %>
    <%= form.text_field :rounds, id: 'new-number-of-rounds' %>
    <%= form.submit "Update number of rounds", :class => 'submit-buttons' %>
  <% end %>
</div>
<hr>
<div id="dashboard-league">
<h2>Current Leagues:</h2>
  <div class="league-column">
    <h3><%= @league1.name %></h3>
    <%= content_tag(:ul) do %>
      <% @league1.competitors.each do |competitor| %>
        <%= content_tag(:li, competitor.name) %>
        <% end %>
    <% end %>
    <%= button_to "Update #{@league1.name}", admin_league_path(@league1), method: :get, :class => 'submit-buttons' %>
  </div>
  <div class="league-column">
    <h3><%= @league2.name %></h3>
    <%= content_tag(:ul) do %>
      <% @league2.competitors.each do |competitor| %>
        <%= content_tag(:li, competitor.name) %>
        <% end %>
    <% end %>
    <%= button_to "Update #{@league2.name}", admin_league_path(@league2), method: :get, :class => 'submit-buttons' %>
  </div>
</div>
<hr>
<div id="leader-board">
<h2>Current Leaders:</h2>
  <div class="league-column">
  <%= @league1.current_leader.try(:name) %>
  <p>Wins: <% if @league1.current_leader.try(:wins) %><%= @league1.current_leader.wins.count %><% end %></p>
  </div>
  <div class="league-column">
  <%= @league2.current_leader.try(:name) %>
  <p>Wins: <% if @league2.current_leader.try(:wins) %><%= @league2.current_leader.wins.count %><% end %></p>
  </div>
</div>
<hr>
<div id="matches">
  <h2>All Matches</h2>
  <div class="league-column">
  <%= content_tag :h3, @league1.name %>
  <%= button_to "Create a new match", new_admin_league_match_path(@league1), method: :get, :class => 'submit-buttons' %>
  <% @league1.matches.each do |match| %>
    <div class="match">
      <p>Round: <%= match.round_number %></p>
      <ul>
      <% match.competitors.each do |competitor| %>
        <li><%=competitor.name %>
        <% if match.try(:winner) == competitor %>
        (winner)
        <% elsif match.try(:loser) == competitor %>
        (loser)
        <% else %>
        <%= button_to "Declare Winner", admin_competitor_match_path(competitor, match), method: :put, :class => 'submit-buttons' %>
        <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
  <div class="league-column">
  <%= content_tag :h3, @league2.name %>
  <%= button_to "Create a new match", new_admin_league_match_path(@league2), method: :get, :class => 'submit-buttons' %>
  <% @league2.matches.each do |match| %>
    <div class="match">
      <p>Round: <%= match.round_number %></p>
      <ul>
      <% match.competitors.each do |competitor| %>
        <li><%=competitor.name %>
        <% if match.try(:winner) == competitor %>
        (winner)
        <% elsif match.try(:loser) == competitor %>
        (loser)
        <% else %>
        <%= button_to "Declare Winner", admin_competitor_match_path(competitor, match), method: :put, :class => 'submit-buttons' %>
        <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/leagues/show.html.erb
<%= render 'admin/homepage_logout_nav_bar' %>

<h1>Update <%= @league.name %></h1>

<div id="update-league-name">
<%= form_for admin_league_path(@league), method: :put do |form| %>

<% if @league.errors.any? %>
  <div>
    <ul>
    <% @league.errors.each do |attribute, message| %>
      <li><%= message[:message] %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form.label :name %>
<%= form.text_field :name, id: "league_name" %>

<%= form.submit "Update League Name", :class => 'submit-buttons' %>

<% end %>
</div>

<div id="update-league-players">
  <h2>Current Players:</h2>
  <%= content_tag(:ul) do %>
    <% @league.competitors.each do |competitor| %>
      <%= content_tag(:li) do %>
        <%= content_tag(:div, competitor.name) %>

        <%= form_for competitor, url: admin_league_competitor_path(@league, competitor) do |form| %>
          <%= form.text_field :name, id: "update_competitor" %>
          <%= form.submit "Rename", :class => 'submit-buttons' %>
        <% end %>

        <%= button_to "Delete", admin_league_competitor_path(@league, competitor), method: :delete, id: "delete-#{competitor.id}", :class => 'submit-buttons' %>
      <% end %>
    <% end %>
  <% end %>

  <%= form_for :competitor, url: admin_league_competitors_path(@league) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, id: "competitor_name" %>
    <%= form.submit "Add Competitor", :class => 'submit-buttons' %>
  <% end %>
</div>

app/views/admin/matches/new.html.erb
<%= render 'admin/homepage_logout_nav_bar' %>

<h1>Create a new match in league <%= @current_league.name %></h1>
<div>

  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @match, url: {action: "create"}, html: {id: "create_match_form"} do |f| %>
  <div>
    <p class='in_one_line_form'><%= f.label :round_number%>:</p>
    <p class='in_one_line_form'><%= f.select :round_number, @round_options %></p>
  </div>
  <div>
    <p class='in_one_line_form'><%= f.label :first_competitor%>:</p>
    <p class='in_one_line_form'><%= f.select :competitor_one_id, @competitor_options, {include_blank: 'None'} %></p>
  </div>
  <div>
    <p class='in_one_line_form'><%= f.label :second_competitor%>:</p>
    <p class='in_one_line_form'><%= f.select :competitor_two_id, @competitor_options, {include_blank: 'None'} %></p>
  </div>

  <%= f.submit "Create Match", :class => 'submit-buttons', :id => 'create-match-button' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompetitionTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="main-header">
      <h1 id="index-title">Seattle Karate Leagues</h1>
      <div id='fish'><%=image_tag("animated-tropical-fish-4.gif", alt: "Tropical Fish")%></div>
    </header>

    <div class="content-container">
      <%= yield %>
    </div>
    <footer id="main-footer">
       <p id="footer">Competition Tracker is the property of George Williams Rutherford IV | &copy; 2016 | All Rights Reserved</p>
    </footer>
  </body>
</html>

app/views/leagues/index.html.erb
<h1>Current Standings</h1>

<div id="table-container">
  <div id="league-A-container">
    <h3><%= @league1.name %></h3>
    <table class="league-table">
      <thead>
        <tr>
          <th>Player</th>
            <% i = 0 %>
            <% while i < @league1.number_of_rounds do %>
            <th class="col-details">
              <%= i += 1 %>
            </th>
            <% end %>
          <th class="col-details">Wins</th>
        </tr>
      </thead>
      <tbody>
        <% @league1.competitors.all.each do |competitor| %>
          <tr>
            <td class="competitor-name">
            <%= competitor.name %>
            </td>
            <% @league1.number_of_rounds.times do |round| %>

              <td class="col-details">
                <%= competitor.results[:"r#{round + 1}"] || '-' %>
              </td>

            <% end %>
            <td>
              <%= competitor.wins.count %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div id="league-B-container">
    <h3><%= @league2.name %></h3>
    <table class="league-table">
      <thead>
        <tr>
          <th>Player</th>
            <% i = 0 %>
            <% while i < @league2.number_of_rounds do %>
            <th class="col-details">
              <%= i += 1 %>
            </th>
            <% end %>
          <th class="col-details">Wins</th>
        </tr>
      </thead>
      <tbody>
        <% @league2.competitors.all.each do |competitor| %>
          <tr>
            <td class="competitor-name">
            <%= competitor.name %>
            </td>
            <% @league1.number_of_rounds.times do |round| %>

              <td class="col-details">
                <%= competitor.results[:"r#{round + 1}"] || '-' %>
              </td>

            <% end %>
            <td>
              <%= competitor.wins.count %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div id='match-results'>
<h1>Match Results for Round <%= @latest_round %></h1>


</div>